/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursos_proyecto;
import main_proyecto.main;
import alumnos_proyecto.*;
import alumnos_proyecto.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */

public class Cursos_Modificar extends javax.swing.JFrame {
    static Connection conn = null;
    static Statement s = null;
    static ResultSet rs = null;
    DefaultTableModel modelo =  new DefaultTableModel();
    String nombreTabla = "CURSOS_COLEGIO";
    
    /**
     * Creates new form Modificar
     */
    public Cursos_Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_FormMostrar = new javax.swing.JButton();
        jButton_FormEliminar = new javax.swing.JButton();
        jButton_FormInsertar = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Resultados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Salon = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Salon = new javax.swing.JTextField();
        jButton_ModificarRegistro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Grado = new javax.swing.JTextField();
        jLabel_Grado = new javax.swing.JLabel();
        jTextField_Horario = new javax.swing.JTextField();
        jLabel_Horario = new javax.swing.JLabel();
        jLabel_IDMaestro = new javax.swing.JLabel();
        jTextField_IDMaestro = new javax.swing.JTextField();
        jButton_Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_FormMostrar.setText("Mostrar");
        jButton_FormMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormMostrarActionPerformed(evt);
            }
        });

        jButton_FormEliminar.setText("Eliminar");
        jButton_FormEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormEliminarActionPerformed(evt);
            }
        });

        jButton_FormInsertar.setText("Insertar");
        jButton_FormInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormInsertarActionPerformed(evt);
            }
        });

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Titulo.setText("Modificar datos de cursos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Resultado:");

        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Modificar por");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Campos a editar");

        jLabel_Nombre.setText("Nombre");

        jLabel_Salon.setText("Salón");

        jTextField_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreActionPerformed(evt);
            }
        });

        jButton_ModificarRegistro.setText("Modificar");
        jButton_ModificarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarRegistroActionPerformed(evt);
            }
        });

        jLabel_Grado.setText("Grado");

        jLabel_Horario.setText("Horario");

        jLabel_IDMaestro.setText("ID Maestro");

        jButton_Regresar.setText("Regresar");
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_FormInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_FormMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton_FormEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGap(1, 1, 1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Titulo)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(331, 331, 331))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_ModificarRegistro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Salon)
                            .addComponent(jLabel_Grado)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jLabel_Horario)
                            .addComponent(jLabel_IDMaestro))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_IDMaestro)
                            .addComponent(jTextField_Horario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Nombre)
                            .addComponent(jTextField_Grado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Salon, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Titulo)
                    .addComponent(jButton_Regresar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ModificarRegistro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nombre)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Salon)
                    .addComponent(jTextField_Salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Grado)
                    .addComponent(jTextField_Grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Horario)
                    .addComponent(jTextField_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IDMaestro)
                    .addComponent(jTextField_IDMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_FormEliminar)
                    .addComponent(jButton_FormMostrar)
                    .addComponent(jButton_FormInsertar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FormMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormMostrarActionPerformed
        // Botón Cambiar Form a Mostrar Cursos
        this.setVisible(false);
        Cursos_Mostrar mostrar = new Cursos_Mostrar();
        mostrar.setVisible(true);
        mostrar.pack();
    }//GEN-LAST:event_jButton_FormMostrarActionPerformed

    private void jButton_FormEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormEliminarActionPerformed
        // Botón Cambiar Form a Eliminar Cursos
        this.setVisible(false);
        Cursos_Eliminar eliminar = new Cursos_Eliminar();
        eliminar.setVisible(true);
        eliminar.pack();
    }//GEN-LAST:event_jButton_FormEliminarActionPerformed

    private void jButton_FormInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormInsertarActionPerformed
        // Botón Cambiar Form a Insertar Cursos
        this.setVisible(false);
        Cursos_Insertar insertar = new Cursos_Insertar();
        insertar.setVisible(true);
        insertar.pack();
    }//GEN-LAST:event_jButton_FormInsertarActionPerformed

    private void jButton_ModificarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarRegistroActionPerformed
        // Botón Modificar
        String idRegistro = jTextField_ID.getText();
        Boolean idFound = false;
        
        try {
            conn = main.Enlace(conn); // Conexión
            rs = main.EnlEst(rs, nombreTabla); //Query
            ResultSetMetaData rsMd = rs.getMetaData(); //Donde guardamos los resultados
            int cantidadColumnas = rsMd.getColumnCount();
            for (int i=1; i <= cantidadColumnas; i++ ){
                modelo.addColumn(rsMd.getColumnName(i));
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int i=0; i < cantidadColumnas; i++ ){
                    fila[i] = rs.getObject(1);
                    if(i == 0){
                        //Para posicionarse en la columna de los IDs
                        //System.out.println("Item: " + rs.getObject(1).toString());
                        if (rs.getObject(1).toString().equals(idRegistro) ) {
                            idFound = true;
                            System.out.println("¡ID  para modificar encontrado!");
                    }
                    }
                }
                modelo.addRow(fila);
            }
            int cantFilas = modelo.getRowCount();
            rs.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        if (idFound == true){
            //Realizar la modificación
            
            try {
                String argsParaEliminar = "";
                conn = main.Enlace(conn);
                
                if(!(jTextField_Nombre.getText().equals(""))){
                    //Agregar a String de eliminación el registro Nombre
                    argsParaEliminar = argsParaEliminar + "NOMBRECURSO = '" + jTextField_Nombre.getText() + "', ";
                }
                if(!(jTextField_Salon.getText().equals(""))){
                    //Agregar a String de eliminación el registro SALON CURSO
                    argsParaEliminar = argsParaEliminar + "SALONCURSO = '" + jTextField_Salon.getText() + "', ";
                }
                if(!(jTextField_Grado.getText().equals(""))){
                    //Agregar a String de eliminación el registro GRADO CURSO
                    argsParaEliminar = argsParaEliminar + "GRADOCURSO = '" + jTextField_Grado.getText() + "', ";
                }
                if(!(jTextField_Horario.getText().equals(""))){
                    //Agregar a String de eliminación el registro HORARIO CURSO
                    argsParaEliminar = argsParaEliminar + "HORARIOCURSO = '" + jTextField_Horario.getText() + "', ";
                }
                if(!(jTextField_IDMaestro.getText().equals(""))){
                    //Agregar a String de eliminación el registro Sexo
                    argsParaEliminar = argsParaEliminar + "IDMaestro = '" + jTextField_IDMaestro.getText() + "', ";
                }
                
                if(!(argsParaEliminar.equals(""))){
                    // Hay argumentos para eliminar
                    String sqlModificar = "";
                    StringBuilder argsParaEliminar_Mod = new StringBuilder(argsParaEliminar);
                    argsParaEliminar_Mod.setLength(argsParaEliminar.length() - 2);
                    
                    sqlModificar = "UPDATE " + nombreTabla + " SET " + argsParaEliminar_Mod + " WHERE CARNET LIKE '" + idRegistro + "'";
                    System.out.println("sqlModificar: " + sqlModificar);
                    PreparedStatement psta = conn.prepareStatement(sqlModificar);
                    psta.execute();
                    psta.close();
                    jLabel_Resultados.setText("¡Se modificó el registro en la Base de Datos exitosamente!");
                } else {
                    // No hay argumentos para eliminar
                    jLabel_Resultados.setText("¡Error! No se ingresó ningún argumento para modificar.");
                }
                
            } catch (Exception e) {
                jLabel_Resultados.setText("Ocurrió un error al intentar modificar el registro en la DB.");
                System.out.println("Excepción:");
                e.printStackTrace();
                System.out.println(e.getCause());
            }            
            
        } else {
            jLabel_Resultados.setText("No es posible modificar el registro porque no existe en la BD.");
            System.out.println("No es posible modificar el registro porque no existe en la BD.");
        }
        jTextField_ID.setText("");
        jTextField_Nombre.setText("");
        jTextField_Salon.setText("");
        jTextField_Grado.setText("");
        jTextField_Horario.setText("");
        jTextField_IDMaestro.setText("");
    }//GEN-LAST:event_jButton_ModificarRegistroActionPerformed

    private void jTextField_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreActionPerformed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
        // Botón para Regresar a Menú Principal
        Menu_Cursos menu = new Menu_Cursos();
        menu.setVisible(true);
        this.setVisible(false);
        menu.pack();
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos_Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_FormEliminar;
    private javax.swing.JButton jButton_FormInsertar;
    private javax.swing.JButton jButton_FormMostrar;
    private javax.swing.JButton jButton_ModificarRegistro;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Grado;
    private javax.swing.JLabel jLabel_Horario;
    private javax.swing.JLabel jLabel_IDMaestro;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Resultados;
    private javax.swing.JLabel jLabel_Salon;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JTextField jTextField_Grado;
    private javax.swing.JTextField jTextField_Horario;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_IDMaestro;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Salon;
    // End of variables declaration//GEN-END:variables
}
