/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursos_proyecto;
import main_proyecto.main;
import alumnos_proyecto.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Cursos_Insertar extends javax.swing.JFrame {
    static Connection conn = null;
    String nombreTabla = "CURSOS_COLEGIO";
    
    /**
     * Creates new form InsertarAlumnos
     */
    public Cursos_Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreCurso = new javax.swing.JLabel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_SalonCurso = new javax.swing.JLabel();
        jTextField_GradoCurso = new javax.swing.JTextField();
        jButton_Ingresar = new javax.swing.JButton();
        jButton_FormMostrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Resultados = new javax.swing.JLabel();
        jButton_FormModificar = new javax.swing.JButton();
        jLabel_GradoCurso = new javax.swing.JLabel();
        jButton_FormEliminar = new javax.swing.JButton();
        jLabel_HorarioCurso = new javax.swing.JLabel();
        jLabel_IDMaestro = new javax.swing.JLabel();
        jLabel_NombreMaestro = new javax.swing.JLabel();
        jTextField_HorarioCurso = new javax.swing.JTextField();
        jTextField_IDMaestro = new javax.swing.JTextField();
        jTextField_NombreMaestro = new javax.swing.JTextField();
        jTextField_NombreCurso = new javax.swing.JTextField();
        jTextField_SalonCurso = new javax.swing.JTextField();
        jLabel_IDCurso = new javax.swing.JLabel();
        jTextField_IDCurso = new javax.swing.JTextField();
        jButton_Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_NombreCurso.setText("Nombre del curso");

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Titulo.setText("Ingreso de Cursos");

        jLabel_SalonCurso.setText("Salón del curso");

        jButton_Ingresar.setText("Ingresar");
        jButton_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngresarActionPerformed(evt);
            }
        });

        jButton_FormMostrar.setText("Mostrar");
        jButton_FormMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormMostrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultados:");

        jButton_FormModificar.setText("Modificar");
        jButton_FormModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormModificarActionPerformed(evt);
            }
        });

        jLabel_GradoCurso.setText("Grado correspondiente");

        jButton_FormEliminar.setText("Eliminar");
        jButton_FormEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormEliminarActionPerformed(evt);
            }
        });

        jLabel_HorarioCurso.setText("Horario del curso");

        jLabel_IDMaestro.setText("ID del maestro a cargo");

        jLabel_NombreMaestro.setText("Nombre del maestro");

        jLabel_IDCurso.setText("ID del curso");

        jButton_Regresar.setText("Regresar");
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Titulo)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_IDCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_IDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_IDMaestro)
                                    .addComponent(jLabel_HorarioCurso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_IDMaestro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(jTextField_HorarioCurso, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_SalonCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_SalonCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_GradoCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_GradoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel_NombreCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_NombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_FormMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_FormModificar))
                            .addComponent(jLabel_Resultados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_Ingresar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(91, 91, 91)
                        .addComponent(jButton_FormEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_NombreMaestro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jTextField_NombreMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Titulo)
                    .addComponent(jButton_Regresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IDCurso)
                    .addComponent(jTextField_IDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NombreCurso)
                    .addComponent(jTextField_NombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SalonCurso)
                    .addComponent(jTextField_SalonCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GradoCurso)
                    .addComponent(jTextField_GradoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_HorarioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_HorarioCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_IDMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_IDMaestro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NombreMaestro)
                    .addComponent(jTextField_NombreMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton_Ingresar)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_FormEliminar)
                    .addComponent(jButton_FormModificar)
                    .addComponent(jButton_FormMostrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IngresarActionPerformed
        // Botón Insertar
        try {
            conn = main.Enlace(conn);
            String sqlinsertar = "insert into " + nombreTabla + " values (?,?,?,?,?,?,?)";
            PreparedStatement psta = conn.prepareStatement(sqlinsertar);
            psta.setString(1, jTextField_IDCurso.getText());
            psta.setString(2, jTextField_NombreCurso.getText());
            psta.setString(3, jTextField_SalonCurso.getText());
            psta.setString(4, jTextField_GradoCurso.getText());
            psta.setString(5, jTextField_HorarioCurso.getText());
            psta.setString(6, jTextField_IDMaestro.getText());
            psta.setString(7, jTextField_NombreMaestro.getText());
            psta.execute();
            psta.close();
            jLabel_Resultados.setText("¡Registros añadidos a la Base de Datos exitosamente!");
            jTextField_IDCurso.setText("");
            jTextField_NombreCurso.setText("");
            jTextField_SalonCurso.setText("");
            jTextField_GradoCurso.setText("");
            jTextField_HorarioCurso.setText("");
            jTextField_IDMaestro.setText("");
            jTextField_NombreMaestro.setText("");
            
        } catch (Exception e) {
            jLabel_Resultados.setText("Ocurrió un error al intentar guardar los registros en la DB.");
            System.out.println(e.getCause());
        }
    }//GEN-LAST:event_jButton_IngresarActionPerformed

    private void jButton_FormMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormMostrarActionPerformed
        // Botón Cambiar a Form Mostrar Cursos
        this.setVisible(false);
        Cursos_Mostrar mostrar = new Cursos_Mostrar();
        mostrar.setVisible(true);
        mostrar.pack();
    }//GEN-LAST:event_jButton_FormMostrarActionPerformed

    private void jButton_FormModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormModificarActionPerformed
        // Botón Cambiar a Form Modificar Cursos
        this.setVisible(false);
        Cursos_Modificar modificar = new Cursos_Modificar();
        modificar.setVisible(true);
        modificar.pack();
    }//GEN-LAST:event_jButton_FormModificarActionPerformed

    private void jButton_FormEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormEliminarActionPerformed
        // Botón Cambiar a Form Eliminar Cursos
        this.setVisible(false);
        Cursos_Eliminar eliminar = new Cursos_Eliminar();
        eliminar.setVisible(true);
        eliminar.pack();
    }//GEN-LAST:event_jButton_FormEliminarActionPerformed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
        // Botón para Regresar a Menú Principal
        Menu_Cursos menu = new Menu_Cursos();
        menu.setVisible(true);
        this.setVisible(false);
        menu.pack();
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos_Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_FormEliminar;
    private javax.swing.JButton jButton_FormModificar;
    private javax.swing.JButton jButton_FormMostrar;
    private javax.swing.JButton jButton_Ingresar;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_GradoCurso;
    private javax.swing.JLabel jLabel_HorarioCurso;
    private javax.swing.JLabel jLabel_IDCurso;
    private javax.swing.JLabel jLabel_IDMaestro;
    private javax.swing.JLabel jLabel_NombreCurso;
    private javax.swing.JLabel jLabel_NombreMaestro;
    private javax.swing.JLabel jLabel_Resultados;
    private javax.swing.JLabel jLabel_SalonCurso;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JTextField jTextField_GradoCurso;
    private javax.swing.JTextField jTextField_HorarioCurso;
    private javax.swing.JTextField jTextField_IDCurso;
    private javax.swing.JTextField jTextField_IDMaestro;
    private javax.swing.JTextField jTextField_NombreCurso;
    private javax.swing.JTextField jTextField_NombreMaestro;
    private javax.swing.JTextField jTextField_SalonCurso;
    // End of variables declaration//GEN-END:variables
}
