/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursos_proyecto;
import main_proyecto.main;
import alumnos_proyecto.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Cursos_Eliminar extends javax.swing.JFrame {
    static Connection conn = null;
    static Statement s = null;
    static ResultSet rs = null;
    DefaultTableModel modelo =  new DefaultTableModel();
    Boolean idFound = false;
    String NombreTabla = "CURSOS_COLEGIO";
    
    /**
     * Creates new form Eliminar
     */
    public Cursos_Eliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_FormInsertar = new javax.swing.JButton();
        jButton_FormMostrar = new javax.swing.JButton();
        jButton_FormModificar = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Resultados = new javax.swing.JLabel();
        jLabel_Subtitulo1 = new javax.swing.JLabel();
        jLabel_IDCurso = new javax.swing.JLabel();
        jTextField_IDCurso = new javax.swing.JTextField();
        jButton_Confirmar = new javax.swing.JButton();
        jLabel_NombreTitulo = new javax.swing.JLabel();
        jLabel_MaestroTitulo = new javax.swing.JLabel();
        jLabel_Subtitulo2 = new javax.swing.JLabel();
        jButton_Eliminar = new javax.swing.JButton();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Maestro = new javax.swing.JTextField();
        jLabel_GradoTitulo = new javax.swing.JLabel();
        jTextField_Grado = new javax.swing.JTextField();
        jButton_Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_FormInsertar.setText("Insertar");
        jButton_FormInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormInsertarActionPerformed(evt);
            }
        });

        jButton_FormMostrar.setText("Mostrar");
        jButton_FormMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormMostrarActionPerformed(evt);
            }
        });

        jButton_FormModificar.setText("Modificar");
        jButton_FormModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormModificarActionPerformed(evt);
            }
        });

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Titulo.setText("Eliminar Cursos");

        jLabel1.setText("Resultado:");

        jLabel_Subtitulo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Subtitulo1.setText("Eliminar por");

        jLabel_IDCurso.setText("ID del curso:");

        jTextField_IDCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDCursoActionPerformed(evt);
            }
        });

        jButton_Confirmar.setText("Confirmar");
        jButton_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmarActionPerformed(evt);
            }
        });

        jLabel_NombreTitulo.setText("Nombre del curso");

        jLabel_MaestroTitulo.setText("Maestro del curso");

        jLabel_Subtitulo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Subtitulo2.setText("Datos del curso a eliminar");

        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jLabel_GradoTitulo.setText("Grado del curso");

        jTextField_Grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GradoActionPerformed(evt);
            }
        });

        jButton_Regresar.setText("Regresar");
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_FormInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jButton_FormMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jButton_FormModificar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Subtitulo1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_IDCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_IDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jLabel_Resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_Subtitulo2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Titulo)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NombreTitulo)
                            .addComponent(jLabel_MaestroTitulo)
                            .addComponent(jLabel_GradoTitulo))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Grado)
                            .addComponent(jTextField_Nombre)
                            .addComponent(jTextField_Maestro))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Titulo)
                    .addComponent(jButton_Regresar))
                .addGap(28, 28, 28)
                .addComponent(jLabel_Subtitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IDCurso)
                    .addComponent(jTextField_IDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Eliminar))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Subtitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NombreTitulo)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Maestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_MaestroTitulo))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_GradoTitulo))
                .addGap(18, 18, 18)
                .addComponent(jButton_Confirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_FormMostrar)
                    .addComponent(jButton_FormInsertar)
                    .addComponent(jButton_FormModificar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FormInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormInsertarActionPerformed
        // Botón Cambiar a Form Insertar Cursos
        this.setVisible(false);
        Cursos_Insertar insertar = new Cursos_Insertar();
        insertar.setVisible(true);
        insertar.pack();
    }//GEN-LAST:event_jButton_FormInsertarActionPerformed

    private void jButton_FormMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormMostrarActionPerformed
        // Botón Cambiar a Form Mostrar Cursos
        this.setVisible(false);
        Cursos_Mostrar mostrar = new Cursos_Mostrar();
        mostrar.setVisible(true);
        mostrar.pack();
    }//GEN-LAST:event_jButton_FormMostrarActionPerformed

    private void jButton_FormModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormModificarActionPerformed
        // Botón Cambiar a Form Modificar Cursos
        this.setVisible(false);
        Cursos_Modificar modificar = new Cursos_Modificar();
        modificar.setVisible(true);
        modificar.pack();
    }//GEN-LAST:event_jButton_FormModificarActionPerformed

    private void jButton_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmarActionPerformed
        // Botón para confirmar que se quiere eliminar el registro

        String idCurso = jTextField_IDCurso.getText();
        
        if ((idFound == true) || (jLabel_Resultados.getText().equals("¡Carnet encontrado!"))) {
            try {
                conn = main.Enlace(conn);
                String sqlEliminar = "DELETE FROM " + NombreTabla + " WHERE CARNET='" + idCurso + "'";
                PreparedStatement psta = conn.prepareStatement(sqlEliminar);
                psta.execute();
                psta.close();
                jLabel_Resultados.setText("¡Registro eliminado de la Base de Datos exitosamente!");
                jTextField_IDCurso.setText("");
                jTextField_Nombre.setText("");
                jTextField_Maestro.setText("");
                jTextField_Grado.setText("");
                
                infoBox("¡La eliminación del Registro ha sido exitosa!","Información");
            } catch (Exception e) {
                jLabel_Resultados.setText("Ocurrió un error al intentar eliminar el registro en la DB.");
                System.out.println("Excepción:");
                e.printStackTrace();
                System.out.println(e.getCause());
            }
        } else {
            jLabel_Resultados.setText("No se pudo eliminar el registro porque no existía en la BD.");
            System.out.println("No se pudo eliminar el registro porque no existía en la BD.");
        }
        
    }//GEN-LAST:event_jButton_ConfirmarActionPerformed

    private void jTextField_IDCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDCursoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_IDCursoActionPerformed

    public void infoBox(String infoMessage, String titleBar)
        {
            JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
        }
    
    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // Botón Dar de Baja (Mostrar curso que se quiere eliminar)
        
        String idRegistro = jTextField_IDCurso.getText();
        try {
            conn = main.Enlace(conn); // Conexión
            rs = main.EnlEst(rs, NombreTabla); //Query
            ResultSetMetaData rsMd = rs.getMetaData(); //Donde guardamos los resultados
            int cantidadColumnas = rsMd.getColumnCount();
            for (int i=1; i <= cantidadColumnas; i++ ){
                modelo.addColumn(rsMd.getColumnName(i));
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int i=0; i < cantidadColumnas; i++ ){
                    fila[i] = rs.getObject(i+1);
                    if(i == 0){                        
                        //Para posicionarse en la columna de los IDs
                        if (rs.getObject(i+1).toString().equals(idRegistro) ) {
                            idFound = true;
                            System.out.println("¡ID para eliminar encontrado!");
                            jTextField_Nombre.setText(rs.getObject(i+2).toString());
                            jTextField_Maestro.setText(rs.getObject(i+6).toString());
                            jTextField_Grado.setText(rs.getObject(i+4).toString());
                        }
                    }
                }
                modelo.addRow(fila);
            }
            int cantFilas = modelo.getRowCount();
            rs.close();
            conn.close();
            
            if(idFound = false){
                jLabel_Resultados.setText("ID no encontrado. Por favor intente nuevamente.");
            } else {
                jLabel_Resultados.setText("¡Carnet encontrado!");
                infoBox("¡Carnet encontrado! Por favor confirme los datos y proceda a eliminar.","Confirmación");
            }
            
        } catch (Exception ex) {
            jLabel_Resultados.setText("Ocurrió un error tratando de encontrar el carnet consultado."
                    + "Por favor intente nuevamente.");
            ex.printStackTrace();
        }       
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jTextField_GradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GradoActionPerformed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
        // Botón para Regresar a Menú Principal
        Menu_Cursos menu = new Menu_Cursos();
        menu.setVisible(true);
        this.setVisible(false);
        menu.pack();
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos_Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Confirmar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_FormInsertar;
    private javax.swing.JButton jButton_FormModificar;
    private javax.swing.JButton jButton_FormMostrar;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_GradoTitulo;
    private javax.swing.JLabel jLabel_IDCurso;
    private javax.swing.JLabel jLabel_MaestroTitulo;
    private javax.swing.JLabel jLabel_NombreTitulo;
    private javax.swing.JLabel jLabel_Resultados;
    private javax.swing.JLabel jLabel_Subtitulo1;
    private javax.swing.JLabel jLabel_Subtitulo2;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JTextField jTextField_Grado;
    private javax.swing.JTextField jTextField_IDCurso;
    private javax.swing.JTextField jTextField_Maestro;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
