package cursos_proyecto;
import main_proyecto.main;
import alumnos_proyecto.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class Cursos_Mostrar extends javax.swing.JFrame {
    static Connection conn = null;
    static Statement s = null;
    static ResultSet rs = null;
    DefaultTableModel modelo =  new DefaultTableModel();
    String nombreTabla = "CURSOS_COLEGIO";

    public Cursos_Mostrar() {
        initComponents();
        this.jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TotalRegistros = new javax.swing.JLabel();
        jButton_Mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_FormInsertar = new javax.swing.JButton();
        jButton_FormModificar = new javax.swing.JButton();
        jButton_FormEliminar = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jButton_Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_TotalRegistros.setText("Total de registros:");

        jButton_Mostrar.setText("Mostrar");
        jButton_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MostrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton_FormInsertar.setText("Insertar");
        jButton_FormInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormInsertarActionPerformed(evt);
            }
        });

        jButton_FormModificar.setText("Modificar");
        jButton_FormModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormModificarActionPerformed(evt);
            }
        });

        jButton_FormEliminar.setText("Eliminar");
        jButton_FormEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormEliminarActionPerformed(evt);
            }
        });

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Titulo.setText("Mostrar Cursos");

        jButton_Regresar.setText("Regresar");
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_FormInsertar)
                                .addGap(220, 220, 220)
                                .addComponent(jButton_FormModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_FormEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Mostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_TotalRegistros))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Titulo)
                        .addGap(292, 292, 292))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Titulo)
                    .addComponent(jButton_Regresar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Mostrar)
                    .addComponent(jLabel_TotalRegistros))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_FormInsertar)
                    .addComponent(jButton_FormEliminar)
                    .addComponent(jButton_FormModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MostrarActionPerformed
        // Botón Mostrar
        try {
            conn = main.Enlace(conn); // Conexión
            rs = main.EnlEst(rs, nombreTabla); //Query
            ResultSetMetaData rsMd = rs.getMetaData(); //Donde guardamos los resultados
            int cantidadColumnas = rsMd.getColumnCount();
            for (int i=1; i <= cantidadColumnas; i++ ){
                modelo.addColumn(rsMd.getColumnName(i));
            }
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for (int i=0; i < cantidadColumnas; i++ ){
                    fila[i] = rs.getObject(i+1);
                    if(i == 0){
                        System.out.println("Estoy en la primera columna: " + rs.getObject(i+1).toString());
                        if (rs.getObject(i+1).toString().equals("4") ) {
                            System.out.println("Encontré el ID!");
                        }
                    }
                }
                modelo.addRow(fila);
            }
            int cantFilas = modelo.getRowCount();
            jLabel_TotalRegistros.setText("Total de registros: " + cantFilas);
            rs.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_MostrarActionPerformed


    private void jButton_FormInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormInsertarActionPerformed
        // Botón Insertar Registros
        this.setVisible(false);
        Cursos_Insertar insertar = new Cursos_Insertar();
        insertar.setVisible(true);
        insertar.pack();
    }//GEN-LAST:event_jButton_FormInsertarActionPerformed

    private void jButton_FormModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormModificarActionPerformed
        // Botón Modificar
        this.setVisible(false);
        Cursos_Modificar modificar = new Cursos_Modificar();
        modificar.setVisible(true);
        modificar.pack();
    }//GEN-LAST:event_jButton_FormModificarActionPerformed

    private void jButton_FormEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormEliminarActionPerformed
        // Botón Eliminar
        this.setVisible(false);
        Cursos_Eliminar eliminar = new Cursos_Eliminar();
        eliminar.setVisible(true);
        eliminar.pack();
    }//GEN-LAST:event_jButton_FormEliminarActionPerformed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
        // Botón para Regresar a Menú Principal
        Menu_Cursos menu = new Menu_Cursos();
        menu.setVisible(true);
        this.setVisible(false);
        menu.pack();
    }//GEN-LAST:event_jButton_RegresarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos_Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_FormEliminar;
    private javax.swing.JButton jButton_FormInsertar;
    private javax.swing.JButton jButton_FormModificar;
    private javax.swing.JButton jButton_Mostrar;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_TotalRegistros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
