/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursos_proyecto;

import main_proyecto.Form_MenuPrincipal;

/**
 *
 * @author usuario
 */
public class Menu_Cursos extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Cursos
     */
    public Menu_Cursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jButton_FormEliminar = new javax.swing.JButton();
        jButton_FormInsertar = new javax.swing.JButton();
        jButton_FormModificar = new javax.swing.JButton();
        jButton_FormMostrar = new javax.swing.JButton();
        jButton_Regresar = new javax.swing.JButton();

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Titulo.setText("Menú para Cursos");

        jButton_FormEliminar.setText("Formulario Eliminar");
        jButton_FormEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormEliminarActionPerformed(evt);
            }
        });

        jButton_FormInsertar.setText("Formulario Insertar");
        jButton_FormInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormInsertarActionPerformed(evt);
            }
        });

        jButton_FormModificar.setText("Formulario Modificar");
        jButton_FormModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormModificarActionPerformed(evt);
            }
        });

        jButton_FormMostrar.setText("Formulario Mostrar");
        jButton_FormMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormMostrarActionPerformed(evt);
            }
        });

        jButton_Regresar.setText("Menú Principal");
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Regresar)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_Titulo)
                        .addContainerGap(139, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_FormInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_FormEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_FormModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jButton_FormMostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Regresar)
                    .addComponent(jLabel_Titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton_FormMostrar)
                .addGap(18, 18, 18)
                .addComponent(jButton_FormInsertar)
                .addGap(18, 18, 18)
                .addComponent(jButton_FormModificar)
                .addGap(18, 18, 18)
                .addComponent(jButton_FormEliminar)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FormMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormMostrarActionPerformed
        // Botón Cambiar a Form Mostrar
        Cursos_Mostrar formMostrar = new Cursos_Mostrar();
        formMostrar.setVisible(true);
        this.setVisible(false);
        formMostrar.pack();
    }//GEN-LAST:event_jButton_FormMostrarActionPerformed

    private void jButton_FormInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormInsertarActionPerformed
        // Botón Cambiar a Form Insertar
        Cursos_Insertar formInsertar = new Cursos_Insertar();
        formInsertar.setVisible(true);
        this.setVisible(false);
        formInsertar.pack();
    }//GEN-LAST:event_jButton_FormInsertarActionPerformed

    private void jButton_FormModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormModificarActionPerformed
        // Botón Cambiar a Form Modificar
        Cursos_Modificar formModificar = new Cursos_Modificar();
        formModificar.setVisible(true);
        this.setVisible(false);
        formModificar.pack();
    }//GEN-LAST:event_jButton_FormModificarActionPerformed

    private void jButton_FormEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormEliminarActionPerformed
        // Botón Cambiar a Form Eliminar
        Cursos_Eliminar formEliminar = new Cursos_Eliminar();
        formEliminar.setVisible(true);
        this.setVisible(false);
        formEliminar.pack();
    }//GEN-LAST:event_jButton_FormEliminarActionPerformed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
        // Botón para Regresar a Menú Principal
        this.setVisible(false);
        
//        Form_MenuPrincipal form_Menu = new Form_MenuPrincipal();
//        form_Menu.setVisible(true);
//        this.setVisible(false);
//        form_Menu.pack();
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Cursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_FormEliminar;
    private javax.swing.JButton jButton_FormInsertar;
    private javax.swing.JButton jButton_FormModificar;
    private javax.swing.JButton jButton_FormMostrar;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel_Titulo;
    // End of variables declaration//GEN-END:variables
}
